use_frameworks!

target 'OrgFoundation_Example' do
  pod 'OrgFoundation', :path => '../'

  target 'OrgFoundation_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
